# Flatpak (Extra installation mode)

add = "flatpak --installation=extra install #:? -y"
remove = "flatpak --installation=extra uninstall #:? -y"

plural_name = "flatpak_extra"

hook_name = "flatpak_extra"

[config]
many_args = true
