# Flatpak repos (Extra installation mode)

add = "flatpak --installation=extra remote-add --if-not-exists #:?"
remove = "flatpak --installation=extra remote-delete #:?"

plural_name = "flatpak_repos_extra"

hook_name = "flatpak_repos_extra"

[config]
many_args = false
