#Notes;
#This gen.toml is ready for a davincibox install
#Don't uninstall native firefox pkg cuz of FDM

#Software that does support wayland but needs a flag/etc;
#Wine,LibreSprite,Spotify,Chromium

#Software that doesn't support wayland
#Steam,Proton,krita,FFDEC,Ryujinx,Yuzu,FNF,Resolve

#Packages to be installed via Pacman.
[managers.system]
items = [
    "zip",
    "kio-admin",
    "p7zip",
    "mangohud", #Remove once you learn how to use the flatpak pkg
    "lib32-mangohud", #When not using WoW64 mode of wine (for 32bit win games)
    "gamemode",
    "gamescope",
    "ntfs-3g",
    "qt6pas", #This is here cuz of the goverlay AppImage
    "discover",
    "timeshift", #Launch with `sudo -E GDK_BACKEND=wayland timeshift-gtk`
    "gnome-disk-utility", #DO NOT REMOVE THIS
    "xdg-desktop-portal-gtk",
    "vkmark",
    "wireguard-tools",
    "headscale",
    "wine",
    "winetricks",
    "kdialog",
    "zenity",
    "htop",
]
#Disabled pkgs

#Packages to be installed via YaY.
[managers.yay]
items = [
    "lact-bin",
]

#Packages to be installed via AM.
[managers.am]
items = [
    "fdm",
    "steam",
    "brave", #This is here because of XCloud/Fortnite
    "fastfetch",
    "gimp-git", #Switch to flatpak once gimp 3 releases
    "goverlay",
    "vesktop",
]

#Packages to be installed via AM --user mode.
[managers.am_user]
items = [
    "ultimmc",
]

#Repos to be added system wide.
[managers.flatpak_repos]
items = [
    "flathub https://dl.flathub.org/repo/flathub.flatpakrepo",
    "sober https://raw.githubusercontent.com/Twig6943/dotfiles/refs/heads/main/flatpak/repos/sober.flatpakrepo",
]

#Repos to be added as user.
[managers.flatpak_repos_user]
items = [
    "flathub https://dl.flathub.org/repo/flathub.flatpakrepo",
    "sober https://raw.githubusercontent.com/Twig6943/dotfiles/refs/heads/main/flatpak/repos/sober.flatpakrepo",
]

#Repos to be added to the extra installation.
[managers.flatpak_repos_extra]
items = [
    "flathub https://dl.flathub.org/repo/flathub.flatpakrepo",
    "sober https://raw.githubusercontent.com/Twig6943/dotfiles/refs/heads/main/flatpak/repos/sober.flatpakrepo",
]

# Packages to be installed via Flatpak. (System mode)
[managers.flatpak]
items = [
    "flathub com.dec05eba.gpu_screen_recorder", #I have to install this as system 😭
]

# Packages to be installed via Flatpak. (User mode)
[managers.flatpak_user]
items = [
    "flathub net.lutris.Lutris",
    "flathub org.strawberrymusicplayer.strawberry",
    "flathub website.i2pd.i2pd",
    "flathub org.gnome.Boxes",
    "flathub org.mozilla.firefox",
    "flathub io.github.flattool.Warehouse",
    "flathub rs.ruffle.Ruffle",
    "flathub org.synfig.SynfigStudio",
    "flathub com.github.libresprite.LibreSprite",
    "flathub org.kde.akregator",
    "flathub org.kde.kclock",
    "flathub io.gitlab.adhami3310.Impression",
    "flathub org.kde.filelight",
    "flathub com.rustdesk.RustDesk",
    "flathub com.vscodium.codium",
    "flathub org.libreoffice.LibreOffice",
    "flathub org.nickvision.tubeconverter",
    "flathub org.kde.kdenlive",
    "flathub org.libretro.RetroArch",
    "flathub net.davidotek.pupgui2",
    "flathub com.github.Matoking.protontricks",
    "flathub org.freedesktop.Platform.VulkanLayer.MangoHud//23.08",
    "flathub org.freedesktop.Platform.VulkanLayer.gamescope//23.08",
    "flathub org.freedesktop.Platform.VulkanLayer.vkBasalt//23.08",
]

# Packages to be installed via Flatpak. (Extra mode)
[managers.flatpak_extra]
items = [
    "flathub sh.ppy.osu",
    "flathub org.zdoom.GZDoom",
    "flathub net.supertuxkart.SuperTuxKart",
    "flathub io.github.TheWisker.Cavasik",
    "flathub com.github.tchx84.Flatseal",
    "flathub org.kde.krita",
    "flathub org.inkscape.Inkscape",
    "flathub io.mpv.Mpv",
    "flathub ch.openboard.OpenBoard",
    "flathub io.github.peazip.PeaZip",
    "flathub org.tenacityaudio.Tenacity",
    "sober org.vinegarhq.Sober",
]

# Packages to be installed as .flatpak files.
#[managers.flatpak_file]
#items = [
    #"github.com/fn2006/PollyMC",
    #"gitgud.io/Twig6943/resolve-flatpak",
#]
