#Notes
#1.Enable wayland backend on libresprite pkg via flatseal

# Packages to be installed via the native package manager.

#Packages to be installed via Pacman.
[managers.system]
items = [
    "git",
    "yay",
    "zip",
    "p7zip",
    "mangohud",
    "winetricks",
    "vkmark",
    "speedtest-cli",
    "wireguard-tools",
    "tailscale",
    "wine",
    "sway",
    "hyprland",
    "xdg-desktop-portal-wlr",
    "amdvlk",
    "yazi",
    "kvantum",
    "qt5ct",
    "qt6ct",
    "virt-manager",
    "qemu",
    "libvirt",
    "bridge-utils",
    "virt-viewer",
]
#Disabled pkgs

#Packages to be installed via YaY.
[managers.yay]
items = [
    "waydroid",
    "waydroid-image-gapps",
    "grimshot-bin-sway",
    "opencl-amd",
    "lact-bin",
    "wireguard-dkms",
]
#Disabled pkgs
#hardinfo2

#Packages to be installed via AM.
[managers.am]
items = [
    "etcher",
    "fastfetch",
    "vscodium",
    "steam",
    "goverlay",
    "cromite",
    "webcamoid",
    "altus",
    "signal",
    "motrix",
]
#Dısabled pkgs
#wireguard-gui

#Packages to be installed via AM --user mode.
[managers.am_user]
items = [
    "hmcl",
]
#Disabled pkgs
#osu

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    "com.github.KRTirtho.Spotube",
    "com.heroicgameslauncher.hgl",
    "website.i2pd.i2pd",
    "org.qbittorrent.qBittorrent",
    "org.strawberrymusicplayer.strawberry",
    "io.mrarm.mcpelauncher",
    "org.mozilla.firefox",
    "com.github.Matoking.protontricks",
    "com.github.tchx84.Flatseal",
    "dev.bragefuglseth.Keypunch",
    "org.fkoehler.KTailctl",
    "io.gpt4all.gpt4all",
    "io.mpv.Mpv",
    "com.github.ztefn.haguichi",
    "com.vysp3r.ProtonPlus",
    "dev.vencord.Vesktop",
    "im.fluffychat.Fluffychat",
    "io.github.TheWisker.Cavasik",
    "io.github.peazip.PeaZip",
    "org.prismlauncher.PrismLauncher",
    "dev.bragefuglseth.Keypunch",
    "sh.ppy.osu",
    "io.github.shadowmario.fnf-psychengine",
    "tw.ddnet.ddnet",
    "org.ryujinx.Ryujinx",
    "org.duckstation.DuckStation",
    "org.vinegarhq.Sober",
    "org.vinegarhq.Vinegar",
    "net.davidotek.pupgui2",
    "net.werwolv.ImHex",
    "com.nextcloud.desktopclient.nextcloud",
    "com.hunterwittenborn.Celeste",
    "org.audacityteam.Audacity",
    "org.blender.Blender",
    "org.flameshot.Flameshot",
    "io.github.marco_calautti.DeltaPatcher",
    "com.jpexs.decompiler.flash",
    "rs.ruffle.Ruffle",
    "org.synfig.SynfigStudio",
    "com.github.libresprite.LibreSprite",
    "org.inkscape.Inkscape",
    "org.kde.akregator",
    "org.kde.kclock",
    "org.gnome.baobab",
    "org.kde.krdc",
    "com.gitlab.davem.ClamTk",
    "org.kde.krita",
    "org.libreoffice.LibreOffice",
    "org.mozilla.Thunderbird",
    "org.nickvision.tubeconverter",
    "im.riot.Riot",
    "in.srev.guiscrcpy",
    "com.obsproject.Studio",
    "org.freedesktop.Platform.VulkanLayer.MangoHud",
    "org.freedesktop.Platform.VulkanLayer.gamescope",
    "org.freedesktop.Platform.VulkanLayer.vkBasalt",
]
#Disabled pkgs;
#"org.telegram.desktop",
#"com.brave.Browser",
#"org.gnome.Boxes",
#"org.videolan.VLC", #Waiting for wayland
#"net.mullvad.MullvadBrowser",
#"io.gitlab.librewolf-community",
#"ca.desrt.dconf-editor",
#"org.kde.haruna",
