# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    # "intensive_apps",
]

# Packages to be installed via the native package manager.

#Packages to be installed via Pacman.
[managers.system]
items = [
    "git",
    "fastfetch",
    "yay",
    "clamtk",
    "mangohud",
    "winetricks",
    "wireguard-tools",
    "wine",
    "speedtest-cli",
    "sway",
    "hyprland",
    "xdg-desktop-portal-wlr",
    "p7zip",
    "amdvlk",
    "yazi",
    "kvantum",
    "qt5ct",
    "qt6ct",
]

#Packages to be installed via YaY.
[managers.yay]
items = [
    "waydroid",
    "grimshot-bin-sway",
    "opencl-amd",
    "playit-bin",
    "wireguard-dkms",
]

#Disabled pkgs
#hardinfo2

#Packages to be installed via AM.
[managers.am]
items = [
    "etcher",
    "vscodium",
    "steam",
    "heroic-games-launcher",
    "goverlay",
    "wireguard-gui",
    "webcamoid",
    "osu",
    "altus",
    "signal",
    "libresprite",
    "motrix",
]


# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    "com.github.KRTirtho.Spotube",
    "org.strawberrymusicplayer.strawberry",
    "io.mrarm.mcpelauncher",
    "com.github.Matoking.protontricks",
    "com.github.tchx84.Flatseal",
    "com.github.ztefn.haguichi",
    "com.vysp3r.ProtonPlus",
    "dev.vencord.Vesktop",
    "im.fluffychat.Fluffychat",
    "io.github.TheWisker.Cavasik",
    "io.github.peazip.PeaZip",
    "io.github.shadowmario.fnf-psychengine",
    "io.gitlab.librewolf-community",
    "net.davidotek.pupgui2",
    "net.werwolv.ImHex",
    "org.audacityteam.Audacity",
    "org.blender.Blender",
    "org.duckstation.DuckStation",
    "org.flameshot.Flameshot",
    "com.jpexs.decompiler.flash",
    "rs.ruffle.Ruffle",
    "org.synfig.SynfigStudio",
    "org.inkscape.Inkscape",
    "org.kde.akregator",
    "org.kde.kclock",
    "org.kde.krdc",
    "org.kde.krita",
    "org.libreoffice.LibreOffice",
    "org.mozilla.Thunderbird",
    "org.nickvision.tubeconverter",
    "org.ryujinx.Ryujinx",
    "org.vinegarhq.Sober",
    "org.vinegarhq.Vinegar",
    "im.riot.Riot",
    "org.videolan.VLC",
    "in.srev.guiscrcpy",
    "com.obsproject.Studio",
    "org.freedesktop.Platform.VulkanLayer.MangoHud",
    "org.freedesktop.Platform.VulkanLayer.gamescope",
    "org.freedesktop.Platform.VulkanLayer.vkBasalt",
]
