#Notes;
#Install PollyMC's .flatpak file from github.com/fn2006/PollyMC/releases 

#Software that doesn't support wayland
#Steam,krita,FFDEC,Ryujinx,Yuzu,FNF

#Software that does support wayland but needs a flag/etc;
#LibreSprite,Spotify,Chromium

# Packages to be installed via the native package manager.

#Packages to be installed via Pacman.
[managers.system]
items = [
    "git",
    "yay",
    "zip",
    "p7zip",
    "mangohud",
    "winetricks",
    "vkmark",
    "speedtest-cli",
    "wireguard-tools",
    "headscale",
    "wine",
    "sway",
    "hyprland",
    "xdg-desktop-portal-wlr",
    "amdvlk",
    "yazi",
    "kvantum",
    "qt5ct",
    "qt6ct",
    "virt-manager",
    "qemu",
    "libvirt",
    "bridge-utils",
    "virt-viewer",
]
#Disabled pkgs

#Packages to be installed via YaY.
[managers.yay]
items = [
    "waydroid",
    "waydroid-image-gapps",
    "gimp-git", #Switch to flatpak once gimp 3 releases
    "grimshot-bin-sway",
    "opencl-amd",
    "lact-bin",
    "wireguard-dkms",
]
#Disabled pkgs
#hardinfo2

#Packages to be installed via AM.
[managers.am]
items = [
    "etcher",
    "fastfetch",
    "vscodium",
    "steam",
    "goverlay",
    "webcamoid",
    "altus",
    "cromite",
    "duckstation", #Using AppImage cuz of wayland support
]
#Dısabled pkgs
#cromite
#wireguard-gui

#Packages to be installed via AM --user mode.
[managers.am_user]
items = [
    "",
]
#Disabled pkgs
#osu

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    "com.github.KRTirtho.Spotube",
    "org.strawberrymusicplayer.strawberry",
    "com.heroicgameslauncher.hgl",
    "website.i2pd.i2pd",
    "dev.deedles.Trayscale",
    "com.github.ztefn.haguichi",
    "net.agalwood.Motrix",
    "org.qbittorrent.qBittorrent",
    "org.mozilla.firefox",
    "com.brave.Browser",
    "com.github.tchx84.Flatseal",
    "io.gpt4all.gpt4all",
    "io.mpv.Mpv",
    "io.github.TheWisker.Cavasik",
    "io.github.peazip.PeaZip",
    "dev.bragefuglseth.Keypunch",
    "sh.ppy.osu",
    "io.mrarm.mcpelauncher",
    "io.github.shadowmario.fnf-psychengine",
    "tw.ddnet.ddnet",
    "org.ryujinx.Ryujinx",
    "org.duckstation.DuckStation",
    "org.vinegarhq.Sober",
    "net.davidotek.pupgui2",
    "com.github.Matoking.protontricks",
    "org.gnome.GHex",
    "com.nextcloud.desktopclient.nextcloud",
    "org.blender.Blender",
    "io.github.marco_calautti.DeltaPatcher",
    "com.jpexs.decompiler.flash",
    "rs.ruffle.Ruffle",
    "org.synfig.SynfigStudio",
    "com.github.libresprite.LibreSprite",
    "org.inkscape.Inkscape",
    "org.kde.akregator",
    "org.kde.kclock",
    "org.gnome.baobab",
    "com.rustdesk.RustDesk",
    "com.gitlab.davem.ClamTk",
    "org.kde.krita",
    "org.libreoffice.LibreOffice",
    "org.nickvision.tubeconverter",
    "im.riot.Riot",
    "org.signal.Signal",
    "dev.vencord.Vesktop",
    "in.srev.guiscrcpy",
    "com.obsproject.Studio",
    "com.dec05eba.gpu_screen_recorder",
    "org.tenacityaudio.Tenacity",
    "org.freedesktop.Platform.VulkanLayer.MangoHud",
    "org.freedesktop.Platform.VulkanLayer.gamescope",
    "org.freedesktop.Platform.VulkanLayer.vkBasalt",
]
#Disabled pkgs;
#org.videolan.VLC #Waiting for wayland #USE MPV FOR THE TIME BEING
#net.werwolv.ImHex #Waiting for wayland support
#org.flameshot.Flameshot
#org.vinegarhq.Vinegar
#com.vysp3r.ProtonPlus
#org.mozilla.Thunderbird
#im.fluffychat.Fluffychat
#org.telegram.desktop
#org.gnome.Boxes
#net.mullvad.MullvadBrowser
#io.gitlab.librewolf-community
#ca.desrt.dconf-editor
#org.kde.haruna
#com.hunterwittenborn.Celeste
