#Notes;
#Don't uninstall native firefox pkg cuz of FDM

#Software that does support wayland but needs a flag/etc;
#Wine,LibreSprite,Spotify,Chromium

#Software that doesn't support wayland
#Steam,Proton,krita,FFDEC,Ryujinx,Yuzu,FNF,Resolve

#Packages to be installed via Pacman.
[managers.system]
items = [
    "zip",
    "p7zip",
    "mangohud", #Remove once you learn how to use the flatpak pkg
    "gamescope",
    "qt6pas", #This is here cuz of the goverlay AppImage
    "discover",
    "gnome-disk-utility", #DO NOT REMOVE THIS
    "winetricks",
    "vkmark",
    "wireguard-tools",
    "headscale",
    "wine",
    "htop",
    "virt-manager",
    "qemu",
    "libvirt",
    "bridge-utils",
    "virt-viewer",
]
#Disabled pkgs

#Packages to be installed via YaY.
[managers.yay]
items = [
    "waydroid",
    "binder_linux-dkms",
    "wireguard-dkms",
    "lact-bin",
]

#Packages to be installed via AM.
[managers.am]
items = [
    "cromite",
    "fdm",
    "brave-appimage",
    "fastfetch",
    "vscodium",
    "gimp-git", #Switch to flatpak once gimp 3 releases
    "goverlay",
    "waydroid-helper",
    "webcamoid",
    "heroic-games-launcher",
    "signal",
    "vesktop",
]


#Packages to be installed via AM --user mode.
[managers.am_user]
items = [
    "duckstation", #Using AppImage cuz of wayland support",
    "funkin-psych", #Using AppImage cuz of wayland support",
    "ultimmc",
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    "com.github.KRTirtho.Spotube",
    "org.strawberrymusicplayer.strawberry",
    "website.i2pd.i2pd",
    "dev.deedles.Trayscale",
    "com.github.ztefn.haguichi",
    "org.qbittorrent.qBittorrent",
    "org.mozilla.firefox",
    "im.riot.Riot",
    "org.telegram.desktop",
    "com.github.tchx84.Flatseal",
    "io.gpt4all.gpt4all",
    "io.github.TheWisker.Cavasik",
    "io.github.peazip.PeaZip",
    "org.gnome.GHex",
    "org.blender.Blender",
    "io.github.marco_calautti.DeltaPatcher",
    "com.jpexs.decompiler.flash",
    "rs.ruffle.Ruffle",
    "org.synfig.SynfigStudio",
    "com.github.libresprite.LibreSprite",
    "org.inkscape.Inkscape",
    "org.kde.akregator",
    "org.kde.kclock",
    "io.gitlab.adhami3310.Impression",
    "org.kde.filelight",
    "com.rustdesk.RustDesk",
    "com.gitlab.davem.ClamTk",
    "org.kde.krita",
    "ch.openboard.OpenBoard",
    "org.libreoffice.LibreOffice",
    "org.nickvision.tubeconverter",
    "com.github.unrud.VideoDownloader", #Fallback
    "in.srev.guiscrcpy",
    "io.mpv.Mpv",
    "com.obsproject.Studio",
    "com.dec05eba.gpu_screen_recorder",
    "org.kde.kdenlive",
    "org.tenacityaudio.Tenacity",
    "com.valvesoftware.Steam",
    "org.libretro.RetroArch",
    "org.ryujinx.Ryujinx",
    "net.davidotek.pupgui2",
    "com.github.Matoking.protontricks",
    "sh.ppy.osu",
    "dev.bragefuglseth.Keypunch",
    "net.supertuxkart.SuperTuxKart",
    "io.mrarm.mcpelauncher",
    "org.zdoom.GZDoom",
    "org.vinegarhq.Sober",
    "tw.ddnet.ddnet",
    "org.freedesktop.Platform.VulkanLayer.MangoHud",
    "org.freedesktop.Platform.VulkanLayer.gamescope",
    "org.freedesktop.Platform.VulkanLayer.vkBasalt",
]

# Packages to be installed via Flatpak.
#[managers.flatpak_external]
#items = [
    #"github.com/fn2006/PollyMC",
#]
