#System

add = "sudo pacman -S #:? --noconfirm" # Example: sudo apt install #:?
remove = "sudo pacman -Rns #:? --noconfirm" # Example: sudo apt remove #:?
sync = "eos-update" # Example: sudo apt update
upgrade = "eos-update" # Example: sudo apt upgrade

plural_name = "system packages"

hook_name = "system_packages" # This is used in hooks. (Example: post_system_packages_add)

[config]
many_args = true
