# A list of apps categorized by their source platform

F-Droid.repos = [
 "cromite.org/fdroid/repo",
 "microg.org/fdroid/repo",
]

F-Droid = [
 "org.microg.gms",
 "org.cromite.cromite",
]

Obtanium = [
 "",
]

Play_Store = [
 "",
]
